# Generated by Django 4.0.6 on 2022-07-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='country name ')),
                ('value', models.PositiveIntegerField(verbose_name='value of country ')),
            ],
        ),
    ]
